[2024-10-02 14:21:09|24776|ERROR|__init__.py:113]  _get_source_fast error, info is index.html
[2024-10-02 14:21:09|24776|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\__init__.py", line 128, in index
    return render_template('index.html', name='index')
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "D:\ruanjian\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\ruanjian\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "D:\ruanjian\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\ruanjian\Python\Python310\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

[2024-10-02 14:21:26|4060|ERROR|__init__.py:113]  _get_source_fast error, info is index.html
[2024-10-02 14:21:26|4060|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\__init__.py", line 128, in index
    return render_template('index.html', name='index')
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "D:\ruanjian\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\ruanjian\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "D:\ruanjian\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\ruanjian\Python\Python310\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

[2024-10-02 14:23:05|23932|ERROR|__init__.py:113]  send_from_directory error, info is 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-02 14:23:05|23932|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 260, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 308, in send_static_file
    return send_from_directory(
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "D:\ruanjian\Python\Python310\lib\site-packages\werkzeug\utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2024-10-02 14:23:48|8748|INFO|base_model.py:91]  session [2683788338288] and [Part] has an operator: QUERY.
[2024-10-02 14:23:48|8748|INFO|part_view.py:28]  part init successfully
[2024-10-02 14:23:48|5904|INFO|base_model.py:91]  session [2683788340160] and [Part] has an operator: QUERY.
[2024-10-02 14:23:48|5904|INFO|part_view.py:28]  part init successfully
[2024-10-02 14:23:51|23064|INFO|base_model.py:91]  session [2683791867040] and [Vehicle] has an operator: QUERY.
[2024-10-02 14:23:51|23064|INFO|vehicle_view.py:28]  Vehicle init successfully
[2024-10-02 14:23:51|12208|INFO|base_model.py:91]  session [2683791867040] and [Vehicle] has an operator: QUERY.
[2024-10-02 14:23:51|12208|INFO|vehicle_view.py:28]  Vehicle init successfully
[2024-10-02 14:24:01|2536|ERROR|__init__.py:113]  send_from_directory error, info is 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-02 14:24:01|2536|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 260, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 308, in send_static_file
    return send_from_directory(
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "D:\ruanjian\Python\Python310\lib\site-packages\werkzeug\utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2024-10-02 14:24:07|26228|INFO|base_model.py:91]  session [2683792065248] and [Part] has an operator: QUERY.
[2024-10-02 14:24:07|26228|INFO|part_view.py:28]  part init successfully
[2024-10-02 14:24:08|21380|INFO|base_model.py:91]  session [2683792064912] and [Part] has an operator: QUERY.
[2024-10-02 14:24:08|21380|INFO|part_view.py:28]  part init successfully
[2024-10-02 14:24:09|20812|INFO|base_model.py:91]  session [2683792068944] and [RegressPredict] has an operator: QUERY.
[2024-10-02 14:24:09|20812|INFO|sales_view.py:31]  Regress Predict init successfully
[2024-10-02 14:24:09|6392|INFO|base_model.py:91]  session [2683792075424] and [RegressPredict] has an operator: QUERY.
[2024-10-02 14:24:09|6392|INFO|sales_view.py:31]  Regress Predict init successfully
