[2024-01-25 11:29:40|19964|ERROR|__init__.py:114]  _get_source_fast error, info is index.html
[2024-01-25 11:29:40|19964|ERROR|__init__.py:115]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\__init__.py", line 129, in index
    return render_template('index.html', name='index')
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

[2024-01-25 11:29:40|7952|ERROR|__init__.py:114]  _get_source_fast error, info is index.html
[2024-01-25 11:29:40|7952|ERROR|__init__.py:115]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\__init__.py", line 129, in index
    return render_template('index.html', name='index')
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

[2024-01-25 11:32:21|14736|INFO|db_init.py:52]  drop my table successfully
[2024-01-25 11:32:21|14736|INFO|db_init.py:60]  create my table successfully
[2024-01-25 11:32:21|14736|ERROR|db_init.py:86]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "F:\python\pythonSDK310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\python\LogisticsDesign\database\db_init.py", line 81, in excel_to_sql
    data = pd.read_excel(excel_path, engine='openpyxl')
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\excel\_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

[2024-01-25 11:32:21|14736|WARNING|app.py:29]  error code: [112]; err msg: [excel to sql error.]
[2024-01-25 11:33:19|2712|INFO|db_init.py:52]  drop my table successfully
[2024-01-25 11:33:19|2712|INFO|db_init.py:60]  create my table successfully
[2024-01-25 11:33:21|2712|INFO|db_init.py:84]  Import excel data [vehicle] successfully
[2024-01-25 11:33:21|2712|INFO|db_init.py:84]  Import excel data [part] successfully
[2024-01-25 15:26:34|9252|ERROR|__init__.py:114]  _get_source_fast error, info is index.html
[2024-01-25 15:26:34|9252|ERROR|__init__.py:115]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\__init__.py", line 129, in index
    return render_template('index.html', name='index')
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

[2024-01-25 15:26:34|4960|ERROR|__init__.py:114]  _get_source_fast error, info is index.html
[2024-01-25 15:26:34|4960|ERROR|__init__.py:115]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\__init__.py", line 129, in index
    return render_template('index.html', name='index')
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

[2024-01-25 15:27:26|21616|ERROR|__init__.py:114]  send_from_directory error, info is 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-01-25 15:27:26|21616|ERROR|__init__.py:115]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 260, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 308, in send_static_file
    return send_from_directory(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2024-01-25 15:31:39|21816|INFO|base_model.py:91]  session [2110534185120] and [Part] has an operator: QUERY.
[2024-01-25 15:31:39|21816|INFO|base_model.py:91]  session [2110534185120] and [Part] has an operator: QUERY.
[2024-01-25 15:31:39|21816|INFO|part_view.py:31]  part init successfully
[2024-01-25 15:34:35|22988|INFO|base_model.py:91]  session [2075782934640] and [Part] has an operator: QUERY.
[2024-01-25 15:34:35|22988|INFO|base_model.py:91]  session [2075782934640] and [Part] has an operator: QUERY.
[2024-01-25 15:34:35|22988|INFO|part_view.py:32]  part init successfully
[2024-01-25 15:43:19|13512|INFO|base_model.py:91]  session [1446674952304] and [Part] has an operator: QUERY.
[2024-01-25 15:43:19|13512|INFO|part_view.py:32]  part init successfully
[2024-01-25 15:54:54|16992|INFO|base_model.py:91]  session [2421579891184] and [Part] has an operator: QUERY.
[2024-01-25 15:54:54|16992|INFO|part_view.py:32]  part init successfully
[2024-01-25 15:57:51|16240|INFO|base_model.py:91]  session [2421579891616] and [Part] has an operator: QUERY.
[2024-01-25 15:57:51|16240|INFO|part_view.py:32]  part init successfully
[2024-01-25 15:57:51|19860|INFO|base_model.py:91]  session [2421579899920] and [Part] has an operator: QUERY.
[2024-01-25 15:57:51|19860|INFO|part_view.py:32]  part init successfully
[2024-01-25 15:59:13|20888|INFO|base_model.py:91]  session [2421579899200] and [Part] has an operator: QUERY.
[2024-01-25 15:59:13|20888|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:00:04|4652|INFO|base_model.py:91]  session [2421579399024] and [Part] has an operator: QUERY.
[2024-01-25 16:00:04|4652|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:00:05|21408|INFO|base_model.py:91]  session [2421579399024] and [Part] has an operator: QUERY.
[2024-01-25 16:00:05|21408|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:05:14|3948|INFO|base_model.py:91]  session [2421579893824] and [Part] has an operator: QUERY.
[2024-01-25 16:05:14|3948|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:05:15|18940|INFO|base_model.py:91]  session [2421579893728] and [Part] has an operator: QUERY.
[2024-01-25 16:05:15|18940|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:05:19|9084|INFO|base_model.py:91]  session [2421579397968] and [Part] has an operator: QUERY.
[2024-01-25 16:05:19|9084|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:05:52|4460|INFO|base_model.py:91]  session [2421579903808] and [Part] has an operator: QUERY.
[2024-01-25 16:05:52|4460|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:16:32|23316|INFO|base_model.py:91]  session [2421579900064] and [Part] has an operator: QUERY.
[2024-01-25 16:16:32|23316|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:16:33|17676|INFO|base_model.py:91]  session [2421579903376] and [Part] has an operator: QUERY.
[2024-01-25 16:16:33|17676|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:24:34|25216|INFO|base_model.py:91]  session [2421579900688] and [Part] has an operator: QUERY.
[2024-01-25 16:24:34|25216|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:24:34|20908|INFO|base_model.py:91]  session [2421579890992] and [Part] has an operator: QUERY.
[2024-01-25 16:24:34|20908|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:25:17|21404|INFO|base_model.py:91]  session [2421579397872] and [Part] has an operator: QUERY.
[2024-01-25 16:25:17|21404|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:25:18|264|INFO|base_model.py:91]  session [2421579397680] and [Part] has an operator: QUERY.
[2024-01-25 16:25:18|264|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:27:25|21296|INFO|base_model.py:91]  session [2421580988960] and [Part] has an operator: QUERY.
[2024-01-25 16:27:25|21296|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:27:25|15564|INFO|base_model.py:91]  session [2421580989776] and [Part] has an operator: QUERY.
[2024-01-25 16:27:25|15564|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:28:51|23480|INFO|base_model.py:91]  session [2421580990640] and [Part] has an operator: QUERY.
[2024-01-25 16:28:51|23480|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:28:51|4080|INFO|base_model.py:91]  session [2421580988720] and [Part] has an operator: QUERY.
[2024-01-25 16:28:51|4080|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:29:14|18852|INFO|base_model.py:91]  session [2421579397632] and [Part] has an operator: QUERY.
[2024-01-25 16:29:14|18852|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:32:02|16632|INFO|base_model.py:91]  session [2421580989632] and [Part] has an operator: QUERY.
[2024-01-25 16:32:02|16632|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:36:20|16828|INFO|base_model.py:91]  session [2421580991312] and [Part] has an operator: QUERY.
[2024-01-25 16:36:20|16828|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:36:20|22012|INFO|base_model.py:91]  session [2421580992896] and [Part] has an operator: QUERY.
[2024-01-25 16:36:20|22012|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:38:15|25256|INFO|base_model.py:91]  session [2421580990640] and [Part] has an operator: QUERY.
[2024-01-25 16:38:15|25256|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:38:15|24612|INFO|base_model.py:91]  session [2421580994672] and [Part] has an operator: QUERY.
[2024-01-25 16:38:15|24612|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:38:18|24628|INFO|base_model.py:91]  session [2421580995344] and [Part] has an operator: QUERY.
[2024-01-25 16:38:18|24628|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:38:38|23256|INFO|base_model.py:91]  session [2421579397056] and [Part] has an operator: QUERY.
[2024-01-25 16:38:38|23256|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:41:08|23980|INFO|base_model.py:91]  session [2421580992944] and [Part] has an operator: QUERY.
[2024-01-25 16:41:08|23980|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:41:09|4368|INFO|base_model.py:91]  session [2421580991024] and [Part] has an operator: QUERY.
[2024-01-25 16:41:09|4368|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:41:35|18204|INFO|base_model.py:91]  session [2421580990640] and [Part] has an operator: QUERY.
[2024-01-25 16:41:35|18204|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:41:35|22664|INFO|base_model.py:91]  session [2421580996976] and [Part] has an operator: QUERY.
[2024-01-25 16:41:35|22664|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:43:15|12944|INFO|base_model.py:91]  session [2421580996112] and [Part] has an operator: QUERY.
[2024-01-25 16:43:15|12944|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:43:15|2712|INFO|base_model.py:91]  session [2421580995776] and [Part] has an operator: QUERY.
[2024-01-25 16:43:15|2712|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:44:51|23704|INFO|base_model.py:91]  session [2421580998032] and [Part] has an operator: QUERY.
[2024-01-25 16:44:51|23704|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:44:51|23400|INFO|base_model.py:91]  session [2421580999040] and [Part] has an operator: QUERY.
[2024-01-25 16:44:51|23400|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:46:28|22696|INFO|base_model.py:91]  session [2421580995872] and [Part] has an operator: QUERY.
[2024-01-25 16:46:28|22696|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:46:28|21832|INFO|base_model.py:91]  session [2421580999952] and [Part] has an operator: QUERY.
[2024-01-25 16:46:28|21832|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:47:35|9604|INFO|base_model.py:91]  session [2421580997072] and [Part] has an operator: QUERY.
[2024-01-25 16:47:35|9604|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:47:36|23772|INFO|base_model.py:91]  session [2421581000816] and [Part] has an operator: QUERY.
[2024-01-25 16:47:36|23772|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:52:04|23852|INFO|base_model.py:91]  session [2421580992992] and [Part] has an operator: QUERY.
[2024-01-25 16:52:04|23852|INFO|part_view.py:32]  part init successfully
[2024-01-25 16:52:04|21764|INFO|base_model.py:91]  session [2421581001680] and [Part] has an operator: QUERY.
[2024-01-25 16:52:04|21764|INFO|part_view.py:32]  part init successfully
[2024-01-25 18:52:05|720|INFO|base_model.py:91]  session [1787261731936] and [Part] has an operator: QUERY.
[2024-01-25 18:52:05|720|INFO|part_view.py:32]  part init successfully
[2024-01-25 18:52:05|3800|INFO|base_model.py:91]  session [1787261238864] and [Part] has an operator: QUERY.
[2024-01-25 18:52:05|3800|INFO|part_view.py:32]  part init successfully
[2024-01-25 19:04:27|17284|INFO|base_model.py:91]  session [1378566866064] and [Part] has an operator: QUERY.
[2024-01-25 19:04:27|17284|INFO|part_view.py:85]  job search successfully
[2024-01-25 19:05:49|1324|INFO|base_model.py:91]  session [1862590792848] and [Part] has an operator: QUERY.
[2024-01-25 19:05:49|1324|INFO|part_view.py:84]  job search successfully
[2024-01-25 19:13:54|21676|INFO|base_model.py:91]  session [2210419836288] and [Part] has an operator: QUERY.
[2024-01-25 19:13:54|21676|INFO|part_view.py:81]  part search successfully
[2024-01-25 19:14:01|16024|INFO|base_model.py:91]  session [2210419835184] and [Part] has an operator: QUERY.
[2024-01-25 19:14:01|16024|INFO|part_view.py:81]  part search successfully
[2024-01-25 19:14:05|20432|INFO|base_model.py:91]  session [2210419836816] and [Part] has an operator: QUERY.
[2024-01-25 19:14:05|20432|INFO|part_view.py:81]  part search successfully
[2024-01-25 19:14:08|23040|INFO|base_model.py:91]  session [2210419847136] and [Part] has an operator: QUERY.
[2024-01-25 19:14:08|23040|INFO|part_view.py:81]  part search successfully
[2024-01-25 19:14:37|22980|INFO|base_model.py:91]  session [2210419842480] and [Part] has an operator: QUERY.
[2024-01-25 19:14:37|22980|INFO|part_view.py:81]  part search successfully
[2024-01-25 19:14:46|15464|INFO|base_model.py:91]  session [2210419842624] and [Part] has an operator: QUERY.
[2024-01-25 19:14:46|15464|INFO|part_view.py:81]  part search successfully
[2024-01-25 19:15:04|18236|INFO|base_model.py:91]  session [2210419838784] and [Part] has an operator: QUERY.
[2024-01-25 19:15:04|18236|INFO|part_view.py:81]  part search successfully
[2024-01-25 19:15:07|16032|INFO|base_model.py:91]  session [2210419850208] and [Part] has an operator: QUERY.
[2024-01-25 19:15:07|16032|INFO|part_view.py:31]  part init successfully
[2024-01-25 19:15:39|20244|INFO|base_model.py:91]  session [2210419835424] and [Part] has an operator: QUERY.
[2024-01-25 19:15:39|20244|INFO|part_view.py:31]  part init successfully
[2024-01-25 19:16:55|12364|INFO|base_model.py:91]  session [2210419835808] and [Part] has an operator: QUERY.
[2024-01-25 19:16:55|12364|INFO|part_view.py:31]  part init successfully
[2024-01-25 19:17:11|25252|INFO|base_model.py:91]  session [2210419846896] and [Part] has an operator: QUERY.
[2024-01-25 19:17:11|25252|INFO|part_view.py:31]  part init successfully
[2024-01-25 19:21:41|15216|INFO|base_model.py:91]  session [2210464991936] and [Part] has an operator: QUERY.
[2024-01-25 19:21:41|15216|INFO|part_view.py:31]  part init successfully
[2024-01-25 19:21:41|22492|INFO|base_model.py:91]  session [2210419847472] and [Part] has an operator: QUERY.
[2024-01-25 19:21:41|22492|INFO|part_view.py:31]  part init successfully
[2024-01-25 19:59:28|7716|ERROR|__init__.py:114]  send_from_directory error, info is 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-01-25 19:59:28|7716|ERROR|__init__.py:115]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 260, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 308, in send_static_file
    return send_from_directory(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2024-01-25 20:01:02|19208|ERROR|__init__.py:114]  send_from_directory error, info is 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-01-25 20:01:02|19208|ERROR|__init__.py:115]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 260, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 308, in send_static_file
    return send_from_directory(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2024-01-25 20:05:37|24444|INFO|base_model.py:91]  session [2360786816880] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:05:37|24444|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-25 20:06:31|18520|ERROR|__init__.py:116]  send_from_directory error, info is 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-01-25 20:06:31|18520|ERROR|__init__.py:117]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 260, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 308, in send_static_file
    return send_from_directory(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2024-01-25 20:06:36|24032|INFO|base_model.py:91]  session [2360786826288] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:06:36|24032|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-25 20:08:24|24716|INFO|base_model.py:91]  session [2360786818272] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:08:24|24716|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-25 20:12:04|24232|INFO|base_model.py:91]  session [2360786825472] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:12:04|24232|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-25 20:12:24|16448|ERROR|__init__.py:116]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-25 20:12:24|16448|ERROR|__init__.py:117]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-25 20:12:28|24992|ERROR|__init__.py:116]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-25 20:12:28|24992|ERROR|__init__.py:117]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-25 20:12:31|15240|ERROR|__init__.py:116]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-25 20:12:31|15240|ERROR|__init__.py:117]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-25 20:13:15|23920|INFO|base_model.py:91]  session [1988073560896] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:13:15|23920|INFO|vehicle_view.py:45]  Vehicle explore successfully
[2024-01-25 20:13:15|13760|INFO|base_model.py:91]  session [1988073562768] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:13:15|13760|INFO|vehicle_view.py:45]  Vehicle explore successfully
[2024-01-25 20:13:25|24496|INFO|base_model.py:91]  session [1988073562048] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:13:25|24496|INFO|vehicle_view.py:45]  Vehicle explore successfully
[2024-01-25 20:13:29|13428|INFO|base_model.py:91]  session [1988073558064] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:13:29|13428|INFO|vehicle_view.py:45]  Vehicle explore successfully
[2024-01-25 20:13:32|12684|INFO|base_model.py:91]  session [1988073240224] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:13:32|12684|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-25 20:13:55|20848|INFO|base_model.py:91]  session [1988073562816] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:13:55|20848|INFO|vehicle_view.py:45]  Vehicle explore successfully
[2024-01-25 20:14:17|18152|INFO|base_model.py:91]  session [1988073562144] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:14:17|18152|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-25 20:14:24|3896|INFO|base_model.py:91]  session [1988073562624] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:14:24|3896|INFO|vehicle_view.py:45]  Vehicle explore successfully
[2024-01-25 20:14:28|24544|INFO|base_model.py:91]  session [1988073560704] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:14:28|24544|INFO|vehicle_view.py:45]  Vehicle explore successfully
[2024-01-25 20:14:44|25468|INFO|base_model.py:91]  session [1988074211216] and [Part] has an operator: QUERY.
[2024-01-25 20:14:44|25468|INFO|part_view.py:31]  part init successfully
[2024-01-25 20:14:44|19352|INFO|base_model.py:91]  session [1988074209584] and [Part] has an operator: QUERY.
[2024-01-25 20:14:44|19352|INFO|part_view.py:31]  part init successfully
[2024-01-25 20:14:56|20952|INFO|base_model.py:91]  session [1988073560224] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:14:56|20952|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-25 20:14:56|24204|INFO|base_model.py:91]  session [1988073560224] and [Vehicle] has an operator: QUERY.
[2024-01-25 20:14:56|24204|INFO|vehicle_view.py:23]  Vehicle init successfully
